using System.ComponentModel.DataAnnotations;

namespace VendingService.API.Contracts.VendingMachines;

public sealed record VendingMachineListItem(
    int VendingMachineId,
    string Name,
    string ModelName,
    string ManufacturerName,
    int? CompanyId,
    string? CompanyName,
    int ModemId,
    string? ModemNumber,
    string Address,
    string Place,
    DateOnly CommissioningDate);

public sealed record VendingMachineDetails(
    int VendingMachineId,
    string Name,
    int VendingMachineModelId,
    int WorkModeId,
    int TimeZoneId,
    int VendingMachineStatusId,
    int ServicePriorityId,
    int ProductMatrixId,
    int? CompanyId,
    int ModemId,
    string Address,
    string Place,
    decimal? Latitude,
    decimal? Longitude,
    string InventoryNumber,
    string SerialNumber,
    DateOnly ManufactureDate,
    DateOnly CommissioningDate,
    DateOnly? LastVerificationDate,
    int? VerificationIntervalMonths,
    DateOnly? NextVerificationDate,
    int? ResourceHours,
    DateOnly? NextServiceDate,
    byte? ServiceDurationHours,
    DateOnly? InventoryDate,
    int CountryId,
    int? LastVerificationUserAccountId,
    TimeOnly? WorkingTimeFrom,
    TimeOnly? WorkingTimeTo,
    int? CriticalValuesTemplateId,
    int? NotificationTemplateId,
    int? ManagerUserAccountId,
    int? EngineerUserAccountId,
    int? TechnicianOperatorUserAccountId,
    string? KitOnlineCashRegisterId,
    string? Notes,
    IReadOnlyList<int> PaymentSystemIds,
    DateTime CreatedAt);

public sealed record CreateVendingMachineRequest
(
    [Required] string Name,
    [Required] int VendingMachineModelId,
    [Required] int WorkModeId,
    [Required] int TimeZoneId,
    [Required] int VendingMachineStatusId,
    [Required] int ServicePriorityId,
    [Required] int ProductMatrixId,
    int? CompanyId,
    int? ModemId,
    [Required] string Address,
    [Required] string Place,
    decimal? Latitude,
    decimal? Longitude,
    [Required] string InventoryNumber,
    [Required] string SerialNumber,
    [Required] DateOnly ManufactureDate,
    [Required] DateOnly CommissioningDate,
    DateOnly? LastVerificationDate,
    int? VerificationIntervalMonths,
    int? ResourceHours,
    DateOnly? NextServiceDate,
    byte? ServiceDurationHours,
    DateOnly? InventoryDate,
    [Required] int CountryId,
    int? LastVerificationUserAccountId,
    TimeOnly? WorkingTimeFrom,
    TimeOnly? WorkingTimeTo,
    int? CriticalValuesTemplateId,
    int? NotificationTemplateId,
    int? ManagerUserAccountId,
    int? EngineerUserAccountId,
    int? TechnicianOperatorUserAccountId,
    string? KitOnlineCashRegisterId,
    string? Notes,
    [MinLength(1)] List<int> PaymentSystemIds
);

public sealed record UpdateVendingMachineRequest
(
    [Required] string Name,
    [Required] int VendingMachineModelId,
    [Required] int WorkModeId,
    [Required] int TimeZoneId,
    [Required] int VendingMachineStatusId,
    [Required] int ServicePriorityId,
    [Required] int ProductMatrixId,
    int? CompanyId,
    int? ModemId,
    [Required] string Address,
    [Required] string Place,
    decimal? Latitude,
    decimal? Longitude,
    [Required] string InventoryNumber,
    [Required] string SerialNumber,
    [Required] DateOnly ManufactureDate,
    [Required] DateOnly CommissioningDate,
    DateOnly? LastVerificationDate,
    int? VerificationIntervalMonths,
    int? ResourceHours,
    DateOnly? NextServiceDate,
    byte? ServiceDurationHours,
    DateOnly? InventoryDate,
    [Required] int CountryId,
    int? LastVerificationUserAccountId,
    TimeOnly? WorkingTimeFrom,
    TimeOnly? WorkingTimeTo,
    int? CriticalValuesTemplateId,
    int? NotificationTemplateId,
    int? ManagerUserAccountId,
    int? EngineerUserAccountId,
    int? TechnicianOperatorUserAccountId,
    string? KitOnlineCashRegisterId,
    string? Notes,
    [MinLength(1)] List<int> PaymentSystemIds
);

